version: '3'
services:
#  spring:
#    build: ./backend
#    ports:
#      - "8082:8082"
#    depends_on:
#      - mysqldb

  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'dodam'
      MYSQL_USER: 'dodam'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    volumes:
      - mysqldb-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - mysqldb
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysqldb
      PMA_PORT: 3306


volumes:
  mysqldb-data: