"""remove_speech_settings_table

Revision ID: 1098e3c26b67
Revises: 63d3ee30154f
Create Date: 2024-06-04 17:28:28.940236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1098e3c26b67'
down_revision: Union[str, None] = '63d3ee30154f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'speech')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('speech', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
