"""add_last_name_to_Profile_table

Revision ID: 3060015f8a55
Revises: 1098e3c26b67
Create Date: 2024-07-12 21:46:46.093502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3060015f8a55'
down_revision: Union[str, None] = '1098e3c26b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('last_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'last_name')
    # ### end Alembic commands ###
