"""create_messages_table

Revision ID: 63d3ee30154f
Revises: 715968d58aac
Create Date: 2024-05-26 01:41:42.664500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '63d3ee30154f'
down_revision: Union[str, None] = '715968d58aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'messages',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('conversation_id', sa.Integer, sa.ForeignKey('conversations.id'), nullable=False),
        sa.Column('time', sa.DateTime, nullable=False),
        sa.Column('speaker', sa.String(length=255), nullable=False),
        sa.Column('content', sa.String(length=512), nullable=False),
        sa.Column('voice', sa.String(length=512), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###