"""create_conversations_table

Revision ID: 715968d58aac
Revises: 8daadbbc13ff
Create Date: 2024-05-26 01:36:10.974786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '715968d58aac'
down_revision: Union[str, None] = '8daadbbc13ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'conversations',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('user', sa.Integer, nullable=False),
        sa.Column('date', sa.Date, nullable=False),
        sa.Column('summary', sa.String(length=1024), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversations')
    # ### end Alembic commands ###