"""create test table

Revision ID: fb04dd70fc69
Revises: 59dded495390
Create Date: 2024-04-30 20:38:34.592988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb04dd70fc69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_examples_id', table_name='examples')
    op.drop_index('ix_examples_name', table_name='examples')
    op.drop_table('examples')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examples',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index('ix_examples_name', 'examples', ['name'], unique=False)
    op.create_index('ix_examples_id', 'examples', ['id'], unique=False)
    # ### end Alembic commands ###
